#Hugo configuration
title = "asfd"
baseURL = "https:\/\/https:\/\/www.google.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
firstpartycookies = true
cookiedomain = "google.com"
